### ISSUE TITLE
Make it easier for google to ban fingerprints

### ISSUE THREAD

**Issue by tommaier123** [TheFreeman193/PIFS#3]
Won't this repository make it trivial for google to ban every fingerprint in it. They can just download it and ban everything.
The only way we have any chance of using spoofed fingerprints longterm is if people learn how to find them on their own.
The main thing this repository will accomplish is burning a whole bunch of fingerprints all at once.

**Comment by TheFreeman193** [comment]
Hi there, I believe you have a few misunderstandings here. Google knows the relevant build properties of every Android build instance that's ever used Play Services and, if they wanted to, they could block software-backed integrity for any and all spoofed device profiles easily with or without access to this repository. Even if they didn't already have such information, the public repositories of build properties that were the sources of these JSONs are no less easy a target.

At present, they appear to be "banning" only fingerprints that are used excessively enough to stand out like those included as default values in PIF modules. By having far fewer people using the same fingerprints we substantially reduce the risk of them being blocked. Additionally, this collection is a mere 5% of the device profiles acquired from public dumps by my automation scripts over a 48-hour period and is not curated.

The real issue here is that the Play Integrity servers can still differentiate real and spoofed devices. Android instances on real devices with "blocked" fingerprints appear to achieve `DEVICE` integrity without hardware-backed key attestation and we still don't entirely understand how. 

You are correct in that ideally, everyone should be able to pick a device profile from the web, create a PIF-compatible JSON file, and use it for their device. For a number of people this is just not possible; whether that's due to knowledge, time constraints, web filters, or any number of other reasons. If you're able to do this - awesome! I would ask kindly, however, that you don't make rash complaints based on incorrect assumptions when there are those in less privileged positions for whom this collection is a valuable and necessary resource.

You're welcome to read my numerous similar replies where this has been brought up before, such as [here](https://old.reddit.com/r/Magisk/comments/18myolm/news_custom_pifjson_files_collection_for_play/ke7jzba/), [here](https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/post-89229465), and [here](https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/post-89239105).

**Comment by tommaier123** [comment]
I have randomly tested about 10 fingerprints and only one worked worked so I assume that most are already blocked.

**Comment by TheFreeman193** [comment]
This ratio seems about right. Because the collection is a random subset of collected public device profiles, you can expect that many will not work, which is also true if trying random ones found on the public web. Some of the profiles are too old or too new, are development or unsigned builds, and some may work if you tweak one or two of the properties.

This collection is by design not curated/filtered, though, and doing so might actually tempt Google engineers to crawl and mass-block. There are a handful of fingerprints that worked when this collection was first published and are now blocked, but looking at my monitoring set of tested-working ones from the published collection, 48/50 are still passing as of Tuesday.
