### ISSUE TITLE
What Play Integrity checks should this pass?

### ISSUE THREAD

**Issue by joshuawilde** [TheFreeman193/PIFS#6]
Of all of the verdicts listed here : https://developer.android.com/google/play/integrity/verdicts

Does it pass all of them? or only some of them?

Thanks.

**Comment by TheFreeman193** [comment]
The modules this collection is designed to work with (see the readme) are designed to help you pass the `MEETS_BASIC_INTEGRITY` and `MEETS_DEVICE_INTEGRITY` verdicts on devices that otherwise wouldn't, such as those running third party firmware like LineageOS or AOSP builds.

For most apps and services, these verdicts are all that matter and you don't need to pass the `MEETS_STRONG_INTEGRITY` to enable most apps and the play features that they depend on. The `MEETS_VIRTUAL_INTEGRITY` verdict is for emulators and not relevant to real devices.

An important point to consider is that in order to run a module that uses JSON profiles from this collection, the device must be rooted, and some apps can detect this and refuse to work even if you pass the needed Play integrity verdicts.

Finally, this collection is simply a distillation of device properties publicly available online, and some profiles won't pass the two verdicts needed. This is the purpose of the script which automates swapping in JSON profiles to test.
